name: SonarQube Binding

on: [push, pull_request, workflow_dispatch]

jobs:
  sonarqube-binding:
    runs-on: ubuntu-latest

    steps:
      - name: Check if GitHub DevOps Binding Exists in SonarQube
        id: check-binding
        run:  |
          response=$(curl -u ${{ secrets.SONAR_USER_TOKEN }}: -X GET '${{ secrets.SONAR_HOST_URL }}api/alm_settings/get_binding?project=${{ secrets.PROJECT_KEY }}')
          echo "response=$response" >> $GITHUB_ENV
          echo "response=$response"

      - name: Apply GitHub DevOps Binding in SonarQube
        run: |
          case "${response}" in
            *"is not bound to any DevOps Platform"*)
              echo "The condition was met, adding the alm binding."
              echo "curl -u ${{ secrets.SONAR_USER_TOKEN }}: -X POST 'https://artpal.ngrok.io/api/alm_settings/set_github_binding?almSetting=${{ secrets.SQ_DEVOPS_INTEGRATION_NAME }}&monorepo=false&project=${{ secrets.PROJECT_KEY }}&repository=${{ secrets.REPOSITORY_NAME }}'"
              curl -u ${{ secrets.SONAR_USER_TOKEN }}: -X POST '${{ vars.SONAR_URL }}?almSetting=${{ secrets.SQ_DEVOPS_INTEGRATION_NAME }}&monorepo=false&project=${{ secrets.PROJECT_KEY }}&repository=${{ secrets.REPOSITORY_NAME }}'
            ;;
          *)
            echo "The condition was not met, so the task was not executed."
            ;;
          esac
